jose_test/apps/products/urls.py
from django.contrib import admin
from apps.products.views import index_products, ProductList, ProductCreate, ProductUpdate, ProductDelete
from django.urls import path, re_path, include
app_name = 'products'
urlpatterns = [
    path('', index_products, name='inicio'),
    path('products/listar', ProductList.as_view(), name='products_listar'),
    path('products/nueva', ProductCreate.as_view(), name='products_crear'),
    path('products/editar/<pk>/', ProductUpdate.as_view(), name='products_editar'),
    path('products/eliminar/<pk>/', ProductDelete.as_view(), name='products_eliminar'),
]

jose_test/apps/stores/urls.py
from django.contrib.auth.decorators import login_required
from apps.stores.views import listadousuarios, index, store_view, store_list, store_edit, store_delete, StoreList, StoreCreate, StoreUpdate, StoreDelete
from django.urls import path, re_path, include
app_name = 'stores'
urlpatterns = [
    path('',index,name='index'),
    path('nuevo/',login_required(StoreCreate.as_view()),name='store_crear'),
    path('listar/',login_required(StoreList.as_view()),name='store_listar'),
    path('editar/<pk>/',login_required(StoreUpdate.as_view()),name='store_editar'),
    path('eliminar/<pk>/',login_required(StoreDelete.as_view()),name='store_eliminar'),
    path('listado/', listadousuarios,name='listado'),
]

jose_test/jose_test/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as path
from django.contrib.auth.views import logout_then_login, LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include(('apps.stores.urls','store'), namespace='store')),
    path('products/',include(('apps.products.urls','products'), namespace='products')),
    path('user/',include(('apps.user.urls','user'), namespace='user')),
    path('accounts/login/', LoginView.as_view(template_name='index.html',success_url=reverse_lazy('store_listar')), name='login'),
    path('logout/', logout_then_login, name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         {'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name="password_reset_confirm"),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name="password_reset_complete"),
]

jose_test/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
</head>
<head>
    {% block extrastatic %}
    {% endblock %}

    <link rel="stylesheet" href="https://bootswatch.com/3/darkly/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" ref="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} Title {% endblock %}</title>
</head>
<body>
<div class="container">

    {% block navbar %}
        <div class="bs-docs-section clearfix">
            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-component">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-expanded="false">Productos<span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'products:products_crear' %}">Registrar Productos</a></li>
                                            <li><a href="{% url 'products:products_listar' %}">Listar Productos</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-expanded="false">Tiendas<span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'stores:store_crear' %}">Registrar Tienda</a></li>
                                            <li><a href="{% url 'stores:store_listar' %}">Listar Tiendas</a></li>
                                        </ul>
                                    </li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                     <li class="dropdown"><a href="https://www.metgroupsas.com/" target="_blank"
                                    onclick="pageTracker._link(this.href); return false;">Met Group</a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                           aria-expanded="false">Opciones<span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href ="{% url 'logout' %}">Salir</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block content %}
    <h5>Este es el contenido del archivo</h5>
    {% endblock %}

    {% block footer %}
    {% endblock %}
</div>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block extrajs %}
    {% endblock %}

</body>
</html>

jose_test/templates/base/header.html
<header>Hola</header>