jose_test/apps/stores/urls.py
from django.contrib.auth.decorators import login_required
from apps.stores.views import listadousuarios, index, store_view, store_list, store_edit, store_delete, StoreList, StoreCreate, StoreUpdate, StoreDelete
from django.urls import path, re_path, include
app_name = 'stores'
urlpatterns = [
    path('',index,name='index'),
    path('nuevo/',login_required(StoreCreate.as_view()),name='store_crear'),
    path('listar/',login_required(StoreList.as_view()),name='store_listar'),
    path('editar/<pk>/',login_required(StoreUpdate.as_view()),name='store_editar'),
    path('eliminar/<pk>/',login_required(StoreDelete.as_view()),name='store_eliminar'),
    path('listado/', listadousuarios,name='listado'),
]

jose_test/jose_test/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as path
from django.contrib.auth.views import logout_then_login, LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include(('apps.stores.urls','store'), namespace='store')),
    path('products/',include(('apps.products.urls','products'), namespace='products')),
    path('user/',include(('apps.user.urls','user'), namespace='user')),
    path('accounts/login/', LoginView.as_view(template_name='index.html',success_url=reverse_lazy('store_listar')), name='login'),
    path('logout/', logout_then_login, name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         {'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name="password_reset_confirm"),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name="password_reset_complete"),
]

jose_test/apps/stores/models.py
from django.db import models

class Store(models.Model):
    nit = models.CharField(max_length = 100)
    name_company = models.CharField(max_length = 100)
    name_commerce = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)
    cellphone= models.CharField(max_length = 100)
    email = models.EmailField()
    website = models.URLField(max_length = 100)
    country = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100)
    city = models.CharField(max_length = 100)
    
    def __str__(self):
        return '{} {}'.format(self.name_company, self.country)

jose_test/apps/stores/forms.py
from django import forms

from apps.stores.models import Store


class StoreForm(forms.ModelForm):

	class Meta:
		model = Store

		fields = [
			'nit',
			'name_company',
			'name_commerce',
			'address',
			'email',
			'cellphone',
			'website',
			'country',
			'state',
			'city',
		]
		labels = {
			'nit': 'Nit',
			'name_company': 'Nombre de la empresa',
			'name_commerce': 'Nombre comercial',
			'address': 'Dirección',
			'email': 'Correo electrónico',
			'cellphone': 'Teléfono',
			'website': 'Sito web',
			'country': 'País',
			'state': 'Departamento',
			'city': 'Ciudad',
		}
		widgets = {
			'nit': forms.TextInput(attrs={'class':'form-control'}),
			'name_company': forms.TextInput(attrs={'class':'form-control'}),
			'name_commerce': forms.TextInput(attrs={'class':'form-control'}),
			'address': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control'}),
			'cellphone': forms.TextInput(attrs={'class':'form-control'}),
			'website': forms.TextInput(attrs={'class':'form-control'}),
			'country': forms.TextInput(attrs={'class':'form-control'}),
			'state': forms.TextInput(attrs={'class':'form-control'}),
			'city': forms.TextInput(attrs={'class':'form-control'}),
		}

jose_test/apps/stores/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from apps.stores.forms import StoreForm
from django.core import serializers
from apps.stores.models import Store
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.

def listadousuarios(request):
	lista = serializers.serialize('json', User.objects.all(), fields=['username', 'first_name'])
	return HttpResponse(lista, content_type='application/json')

def index(request):
	return render(request, 'stores/index.html')

def store_view(request):
	if request.method == 'POST':
		form = StoreForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('stores:store_listar')
	else:
		form = StoreForm()
	return render(request, 'stores/store_form.html', {'form':form})

def store_list(request):
	stores = Store.objects.all()
	contexto = {'stores':stores, 'form':form}
	return render(request, 'stores/store_list.html', contexto)

def store_edit(request, id_store):
	stores = Store.objects.get(id=id_store)
	if request.method == 'GET':
		form = StoreForm(instance=stores)
	else:
		form = StoreForm(request.POST, instance=stores)
		if form.is_valid():
			form.save()
		return redirect('stores:store_listar')
	return render(request, 'stores/store_form.html', {'form':form})

def store_delete(request, id_store):
	stores = Store.objects.get(id=id_store)
	if request.method == 'POST':
		stores.delete()
		return redirect('stores:store_listar')
	return render(request, 'stores/store_delete.html', {'stores':stores})

class StoreList(ListView):
	model = Store
	template_name = 'stores/store_list.html'
	paginate_by = 2

class StoreCreate(CreateView):
	model = Store
	form_class = StoreForm
	template_name = 'stores/store_form.html'
	success_url = reverse_lazy('stores:store_listar')

class StoreUpdate(UpdateView):
	model = Store
	form_class = StoreForm
	template_name = 'stores/store_form.html'
	success_url = reverse_lazy('stores:store_listar')

class StoreDelete(DeleteView):
	model = Store
	template_name = 'stores/store_delete.html'
	success_url = reverse_lazy('stores:store_listar')

jose_test/templates/stores/index.html
{% extends 'base/base.html' %}

{% block title%}
Producto
{% endblock %}


{% block content %}
<h1>Contenido de la aplicación Producto</h1>
{% endblock%}

jose_test/templates/stores/store_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Esta seguro de eliminar la tienda {{ object.name_company }}?</h3>
    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
    <a class="btn btn-default" href="{% url 'store:store_listar' %}">Cancelar</a>
</form>
{% endblock %}

jose_test/templates/stores/store_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit">Registrar</button>
</form>
{% endblock %}

jose_test/templates/stores/store_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>Nit</td>
			<td>Nombre</td>
			<td>Nombre comercial</td>
			<td>Dirección</td>
			<td>Correo electrónico</td>
			<td>Número de teléfono</td>
			<td>Sitio web</td>
			<td>País</td>
			<td>Departamento</td>
			<td>Ciudad</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for store in object_list %}
		<tr>
			<td>{{ store.nit }}</td>
			<td>{{ store.name_company }}</td>
			<td>{{ store.name_commerce }}</td>
			<td>{{ store.address }}</td>
			<td>{{ store.email }}</td>
			<td>{{ store.cellphone }}</td>
			<td>{{ store.website }}</td>
			<td>{{ store.country }}</td>
			<td>{{ store.state }}</td>
			<td>{{ store.city }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'store:store_editar' store.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'store:store_eliminar' store.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de tiendas</h1>
		{% endif %}
	</tbody>
</table> 
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul>
{% endblock%}